from enum import Enum


class ASNStat(Enum):
    IN_PLANNING = 5
    OPEN = 10
    IN_TRANSIT = 20
    RECEIVING_STARTED = 30
    RECEIVING_VERIFIED = 40
    REFUSED = 50
    CANCELED = 60
    PENDING_CANCELED = 70


class ASNDtlStat(Enum):
    ACCEPTED = 4
    REJECTED = 8
    REQUIRES_NEW = 12
    RECEIVING_STARTED = 16
    RECEIVING_COMPLETE = 20
    NOT_RECEIVED = 24
    REFUSED = 28


class POStat(Enum):
    INVALID = 10
    CREATED = 20
    SHIPPER_REJECTED = 100
    VENDOR_REJECTED = 105
    SHIPPER_COUNTERED = 110
    VENDOR_COUNTERED = 115
    PENDING_SHIPPER_ACCEPTANCE = 120
    PENDING_VENDOR_ACCEPTANCE = 130
    RECALLED = 140
    ACCEPTED = 150
    SOURCED = 200
    PARTIALLY_SOURCED = 250
    SOURCING_FAILED = 290
    SCHEDULED = 300
    PARTIALLY_SCHEDULED = 350
    SCHEDULING_FAILED = 390
    ALLOCATED = 400
    PARTIALLY_ALLOCATED = 450
    ALLOCATION_FAILED = 490
    DO_CREATED = 492
    DO_PARTIALLY_CREATED = 496
    RELEASED = 500
    PARTIALLY_RELEASED = 550
    DC_ALLOCATED = 600
    PARTIALLY_DC_ALLOCATED = 650
    IN_WORK = 740
    PARTIALLY_SHIPPED = 800
    SHIPPED = 850
    RECEIVING_STARTED = 920
    RECEIVED = 930
    CANCELED = 940
    CLOSED = 950


class PODtlStat(Enum):
    INVALID = 10
    CREATED = 20
    SHIPPER_REJECTED = 100
    SHIPPER_COUNTERED = 110
    PENDING_SHIPPER_ACCEPTANCE = 120
    PENDING_VENDOR_ACCEPTANCE = 130
    RECALLED = 140
    ACCEPTED = 150
    SOURCED = 200
    SOURCING_FAILED = 290
    SCHEDULED = 300
    SCHEDULING_FAILED = 390
    ALLOCATED = 400
    ALLOCATION_FAILED = 490
    RELEASED = 500
    PARTIALLY_RELEASED = 550
    DC_ALLOCATED = 600
    PARTIALLY_DC_ALLOCATED = 650
    REQUEST_FOR_ROUTING = 700
    IN_WORK = 740
    PARTIALLY_SHIPPED = 800
    SHIPPED = 850
    BACK_ORDERED = 900
    RECEIVING_STARTED = 920
    RECEIVED = 930
    CANCELED = 940
    CLOSED = 950
    DO_CREATED = 492
    VENDOR_REJECTED = 105
    VENDOR_COUNTERED = 115
    DO_PARTIALLY_CREATED = 496


class TaskHdrStat(Enum):
    RELEASED = 10
    PARTIALLY_ASSEMBLED = 13
    RESERVED = 14
    TASK_ASSEMBLED = 15
    IN_DROP_ZONE = 20
    ASSIGNED = 30
    IN_PROGRESS = 40
    LOCKED_DISABLED = 5
    COMPLETE = 90
    CANCELLED = 99


class TaskDtlStat(Enum):
    UNASSIGNED = 0
    RELEASED = 10
    IN_PROGRESS = 40
    ASSIGNED = 50
    TASK_COMPLETE = 90
    DELETED = 99


class AllocStat(Enum):
    PRE_RECEIPT_ALLOCATED = -1
    UNRELEASED_SINGLES_ALLOCATION = -2
    CREATED = 0
    SELECTED_AGAINST_NEED_ID = 50
    PROCESSED = 90
    TASK_DETAIL_CREATED = 91
    CANCELLED = 99


class LPNFacStat(Enum):
    ILPN_IN_TRANSIT = 0
    ILPN_NOT_RECEIVED_SHIPMENT_VERIFIED = 1
    ILPN_IN_WORK_ORDER = 2
    ILPN_WORK_ORDER = 3
    ILPN_PRE_RECEIPT_ALLOCATED_NOT_RECEIVED = 4
    ILPN_PRE_RECEIPT_ALLOCATED_RECEIVED = 6
    ILPN_IN_INVENTORY_NOT_PUTAWAY = 10
    ILPN_PUTAWAY = 30
    ILPN_PARTIALLY_ALLOCATED = 45
    ILPN_ALLOCATED = 50
    ILPN_ALLOCATED_AND_PULLED = 64
    ILPN_PULLED = 65
    ILPN_IN_ACTIVE_STORAGE = 90
    ILPN_IN_CASE_PICK_STORAGE = 91
    ILPN_CONSUMED = 95
    ILPN_CONSUMED_TO_ACTV = 96
    ILPN_CONSUMED_TO_CASE_PICK = 97
    ILPN_CANCELLED = 99
    OLPN_NOT_PRINTED = 0
    OLPN_PRE_RECEIPT_ALLOCATED = 4
    OLPN_PRINTED = 10
    OLPN_RELEASED = 12
    OLPN_IN_PACKING = 15
    OLPN_PACKED = 20
    OLPN_WEIGHED = 30
    OLPN_MANIFESTED = 40
    OLPN_PENDING_LOADING = 45
    OLPN_LOADED_ON_TRUCK = 50
    OLPN_COMPLETED_VAS = 89
    OLPN_SHIPPED = 90
    OLPN_DELIVERED = 95
    OLPN_CANCELLED = 99


class DOStat(Enum):
    SPECIAL_PROCESSING_PENDING = 112
    DRAFT = 100
    PRE_RELEASED = 105
    RELEASED = 110
    SELECTED_FOR_PREVIEW_WAVE = 115
    PARTIALLY_DC_ALLOCATED = 120
    DC_ALLOCATED = 130
    IN_PACKING = 140
    PACKED = 150
    WEIGHED = 160
    MANIFESTED = 170
    LOADED = 180
    SHIPPED = 190
    CANCELLED = 200
    PARTIALLY_SHIPPED = 185
    STAGED = 165
    DELIVERED = 195


class DODtlStat(Enum):
    WAVED = 20
    ALLOCATED = 25
    ORDERED = 30
    PACKED = 40
    SHIPPED_INVOICED = 90
    DELETED = 99


class WaveStat(Enum):
    SHIP_WAVE_COMPLETED = 90


class ManifestStat(Enum):
    OPEN = 10
    CLOSED = 90
    ERROR = 15
    CLOSE_IN_PROCESS = 20
    PRINTED = 30
